if(!Function.prototype.bind)Function.prototype.bind=function(f){if(typeof this!=="function")throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var c=Array.prototype.slice.call(arguments,1),d=this,a=function(){},b=function(){return d.apply(this instanceof a?this:f||window,c.concat(Array.prototype.slice.call(arguments)))};a.prototype=this.prototype;b.prototype=new a;return b};
if(!Array.prototype.some)Array.prototype.some=function(f,c){if(this==null)throw new TypeError;var d=Object(this),a=d.length>>>0;if(typeof f!="function")throw new TypeError;for(var b=0;b<a;b++)if(b in d&&f.call(c,d[b],b,d))return true;return false};if(!Array.prototype.filter)Array.prototype.filter=function(f,c){if(this==null)throw new TypeError;var d=Object(this),a=d.length>>>0;if(typeof f!="function")throw new TypeError;for(var b=[],e=0;e<a;e++)if(e in d){var h=d[e];f.call(c,h,e,d)&&b.push(h)}return b};
if(!Array.prototype.forEach)Array.prototype.forEach=function(f,c){var d,a;if(this==null)throw new TypeError(" this is null or not defined");var b=Object(this),e=b.length>>>0;if({}.toString.call(f)!="[object Function]")throw new TypeError(f+" is not a function");if(c)d=c;for(a=0;a<e;){var h;if(a in b){h=b[a];f.call(d,h,a,b)}a++}};
if(!Array.prototype.indexOf)Array.prototype.indexOf=function(f){if(this==null)throw new TypeError;var c=Object(this),d=c.length>>>0;if(d===0)return-1;var a=0;if(arguments.length>0){a=Number(arguments[1]);if(a!=a)a=0;else if(a!=0&&a!=Infinity&&a!=-Infinity)a=(a>0||-1)*Math.floor(Math.abs(a))}if(a>=d)return-1;for(a=a>=0?a:Math.max(d-Math.abs(a),0);a<d;a++)if(a in c&&c[a]===f)return a;return-1};
if(!Array.prototype.map)Array.prototype.map=function(f,c){var d,a,b;if(this==null)throw new TypeError(" this is null or not defined");var e=Object(this),h=e.length>>>0;if({}.toString.call(f)!="[object Function]")throw new TypeError(f+" is not a function");if(c)d=c;a=Array(h);for(b=0;b<h;){var g;if(b in e){g=e[b];g=f.call(d,g,b,e);a[b]=g}b++}return a};
if(!Array.prototype.reduce)Array.prototype.reduce=function(f){if(this===null||this===undefined)throw new TypeError("Object is null or undefined");var c=0,d=this.length>>0,a;if(typeof f!=="function")throw new TypeError("First argument is not callable");if(arguments.length<2){if(d===0)throw new TypeError("Array length is 0 and no second argument");a=this[0];c=1}else a=arguments[1];for(;c<d;){if(c in this)a=f.call(undefined,a,this[c],c,this);++c}return a};
(function(f,c,d){var a=window[f],b={config:{version:"1.1",fxSpeed:300,lock:{timeout:600,idle:15,lockWhenInactive:false},forms:{pwdmeter:{okayThreshold:80}},settings:{width:450},contents:{sortableOnTouchDevices:false},scollToTop:true,preload:{enabled:true,prefix:""},lang:{appcache:{PLEASE_RELOAD_TITLE:"New version",PLEASE_RELOAD:"A new version of this site is available. Please reload page.",PROMT_RELOAD:"A new version of this site is available. Load it?"}}},utils:{noBubbling:function(e){e.stopPropagation()},
tryF:function(e){return function(){try{e()}catch(h){console.error(h);console.trace()}}},ready:function(e){b.ready.run?b.utils.tryF(e)():c(window).load(b.utils.tryF(e))},loaded:function(e){if(b.loaded.run)b.utils.tryF(e)();else{var h=b.loaded.cb;!h&&(h=[]);c.isFunction(e)?h.push(b.utils.tryF(e)):b.loaded.run=true|h.forEach(function(g){g()});b.loaded.cb=h}},preload:function(e){_.defer(function(){e.forEach(function(h){(new Image).src=b.config.preload.prefix+h})})}},registry:{},register:function(e){var h=
b.registry,g={name:d,func:function(){},wrapper:function(j){j()},init:function(){},check:function(){return true},dependencies:[]};g.name=e;var i=[].slice.call(arguments,1),k=i.length;if(k>1)if(k==3)c.extend(g,{dependencies:i[0],wrapper:i[1],func:i[2]});else k==2&&_.isArray(i[0])&&_.isObject(i[1])?c.extend(g,i[1],{dependencies:i[0]}):c.extend(g,{wrapper:i[0],func:i[1]});else k==1&&_.isObject(i[0])?c.extend(g,i[0]):c.extend(g,{func:i[0]});h[g.name]=function(j,l){l=c.Deferred();require(g.dependencies,
function(){g.init();g.func();j&&j();l.resolve()});return l.promise()};g.wrapper(function(){g.check()&&require(g.dependencies,function(){g.init();g.func()})})},isOldIE:c.browser.msie&&parseInt(c.browser.version)<9,isPhone:window.matchMedia("screen and (max-width: 650px)").matches&&Modernizr.touch,noConflict:function(){window[f]=a;return this}};c(window).load(function(){b.ready.run=true});b.loaded=b.utils.loaded;b.ready=b.utils.ready;window[f]={};c.extend(window[f],b)})("$$",jQuery);