(!window.console||!console.log)&&function(){for(var c=function(){},g="assert clear count debug dir dirxml error exception group groupCollapsed groupEnd info log markTimeline profile profileEnd markTimeline table time timeEnd timeStamp trace warn".split(" "),m=g.length,s=window.console={};m--;)s[g[m]]=c}();(function(c){c.fn.doesHave=function(g){return!!this.has(g).length}})(jQuery);
(function(c){c.fn.insert=function(g){var m=this[0];if(typeof g=="string"){m.innerHTML+=g;return c(m.children)}else if(g.jquery){m.innerHTML+=g.html();return c(m.children)}else return this.append(g)}})(jQuery);(function(c){c.fn.equalHeight=function(){var g=c(this);g.height(Math.max.apply(Math,g.map(function(){return c(this).height()}).get()));return g};c.fn.equalWidth=function(){var g=c(this);g.width(Math.max.apply(Math,g.map(function(){return c(this).width()}).get()));return g}})(jQuery);
(function(c){c.fn.alert=function(g,m){return c(this).each(function(){var s=c(this),k=c.extend({},c.fn.alert.defaults,m,s.data()),h="alert "+k.type;if(k.noMargin)h+=" no-margin";if(k.position)h+=" "+k.position;if(k.closeEverywhere&&!k.sticky)h+=" closeEverywhere";h=c('<div style="display:none" class="'+h+' generated">'+g+"</div>");h.prepend(c("<span>").addClass("icon"));k.sticky||h.find(".icon").after(c("<span>").addClass("close").text("x"));s.prepend(h);h.fadeIn()})};c.fn.alert.defaults={type:"information",
position:"",noMargin:false,sticky:false,closeEverywhere:false}})(jQuery,this);
(function(c){c.fn.validationOptions=function(g){var m=c(this);$$.registry.validation(function(){return m.each(function(){var s=c(this),k=s.validate();if(g.submitHandler){var h=k.settings.submitHandler,o=g.submitHandler;k.settings.submitHandler=function(){o.apply(this,arguments)&&h.apply(this,arguments)};delete g.submitHandler}if(g.invalidHandler)s.on("invalid-form.validate",g.invalidHandler);c.extend(k.settings,g)})})}})(jQuery,this);
(function(c,g){c.fn.initMenu=function(m){var s=c(this),k=c.extend({},{accordeon:true},m,s.data());return s.each(function(){var h=c(this);if(h.hasClass("accordion"))k.accordion=true;h.find("li:has(ul)").children("a").addClass("with_sub").end().children("ul").addClass("sub");var o=h.find(".sub");if(k.accordion){o.show();var t=0,q=c();o.each(function(){var j=c(this),a=j.height();if(a>t){t=a;q=j}});o.hide();q.show();h.height(h.height());q.hide()}else{o.show();h.height(h.height());o.hide()}o.filter(function(){return c(this).prev().is(".open")}).show();
h.find("li a").click($$.utils.noBubbling);h.find("li a").click(function(){var j=c(this),a=j.next(),p=$$.config.fxSpeed*2/3;if(k.accordion)if(a.is(".sub:visible")){a.prev().removeClass("open");o.filter(":visible").slideUp(p);return false}else{if(a.is(".sub:hidden")){o.filter(":visible").slideUp(p);h.find(".open").removeClass("open");a.slideDown(p);a.prev().addClass("open")}}else{if(a.length){a.slideToggle(p);a.prev().toggleClass("open")}else g.location.href=j.attr("href");return false}})})}})(jQuery,
this);
(function(c,g){c.fn.tabbedBox=function(m){m=c.extend({},{fxSpeed:$$.config.fxSpeed/1.2,header:".header",content:".content"},m);var s=c(this).each(function(){var k=function(a,p){if(!a.is(":visible")){var d=c(".actions[rel="+a[0].id+"]");if(p){t.hide();d.show();o.children(":visible").fadeOut(m.fxSpeed,function(){a.fadeIn(m.fxSpeed,function(){a.find(".ui-accordion").not(".toggle").accordion("resize");h.trigger("tab-switch")})})}else{o.children(":visible").hide();a.show();t.hide();d.show()}}},h=c(this),
o=_.isString(m.content)?h.find(m.content):c(m.content),t=h.find(".actions[rel]"),q=_.isString(m.header)?h.find(m.header).find("ul"):c(m.header),j=q.find("li.current").find("a").attr("href");q.is("ul")||(q=q.find("ul"));j||(j=q.find("li").first().find("a").attr("href"));o.children().hide();q.on("click","a",function(){var a=c(this).parent().find("a").attr("href"),p=location.hash,d=q.find("li.current").find("a").attr("href");if(p.split(",").indexOf(d)!=-1)location.hash=p.replace(d,a);else location.hash+=
(p.length&&","||"")+a;return false});c(g).on("hashchange",{anim:true},function(a,p){p=p==undefined&&true||p;var d=location.hash,b;d.trim().split(",").forEach(function(f){var e=o.find(f);if(e.length){b=e;d=f}});if(b==undefined)b=o.find(q.find("li.current").find("a").attr("href"));if(b==undefined||!b.length)b=o.find(q.find("a").first().attr("href"));if(b.length){k(b,p);q.find(".current").removeClass("current");q.find("li:has(a[href=#"+b.attr("id")+"])").addClass("current")}})});c(g).trigger("hashchange",
[false]);return s}})(jQuery,this,document);
(function(c,g,m){c.fn.mslider=function(s){return c(this).each(function(){if(!c(this).data("ready")){c(this).data("ready",true);var k=c(this).hide(),h=c.extend({},{value:50,min:0,max:100,step:1,range:false,values:m,orientation:"horizontal",disabled:false,onslide:null,tooltip:true,format:"0",pattern:"%n"},s,function(){var q={};if(k.val())q.value=k.val();if(k.attr("disabled"))q.disabled=true;return q}(),k.data());if(_.isString(h.value)&&h.value!=""&&h.value.match(/^\d+:\d+$/)){var o=h.value.match(/^(\d+):(\d+)$/);
h.range=[o[1],o[2]]}h.values=h.range==false||h.range=="max"||h.range=="min"?m:_.isArray(h.range)?h.range:c.parseJSON(h.range);h.range=h.range==false?"min":h.range=="max"||h.range=="min"?h.range:true;var t=function(q,j){j?k.val(j[0]+":"+j[1]):k.val(q)};t(h.value,h.values);c("<div>").insertAfter(k).slider({value:h.value,max:h.max,min:h.min,step:h.step,orientation:h.orientation,disabled:h.disabled,slide:function(q,j){t(j.value,j.values);h.onslide&&h.onslide.call(q,j);c(j.handle).find(".slider-tooltip").text(h.pattern.replace("%n",
(new Number(j.value)).numberFormat(h.format+"")))},start:function(q,j){c(j.handle).find(".slider-tooltip").show().text(h.pattern.replace("%n",(new Number(j.value)).numberFormat(h.format+"")))},stop:function(q,j){c(j.handle).find(".slider-tooltip").hide()},range:h.range,values:h.values}).find(".ui-slider-handle").each(function(){h.tooltip&&c('<div class="slider-tooltip">').hide().appendTo(c(this))})}})}})(jQuery,this);
function startTime(){var c=new Date,g=c.getHours(),m=c.getMinutes();c=c.getSeconds();m=checkTime(m);c=checkTime(c);document.getElementById("time").innerHTML=g+":"+m+":"+c;setTimeout(startTime,500)}function checkTime(c){if(c<10)c="0"+c;return c}
(function(c){var g=c.ui.progressbar.prototype._init;c.ui.progressbar.prototype.options.color="blue";c.ui.progressbar.prototype.options.colorize=true;c.ui.progressbar.prototype.options.animate=false;c.ui.progressbar.prototype.options.maxNormal=60;c.ui.progressbar.prototype.options.maxWarn=90;c.ui.progressbar.prototype._init=function(){var m=this,s=this.options,k=this.element,h=["blue","orange","red","grey","auto"];if(s.color&&s.colorize)if(h.indexOf(s.color)==-1)s.color=c.ui.progressbar.prototype.options.color;
s.color=="auto"&&this.element.bind("progressbarchange",function(){var o=parseInt(m.options.value/m.options.max*100);k.removeClass("blue green orange red");if(o<m.options.maxNormal)k.addClass("blue");else o<m.options.maxWarn?k.addClass("orange"):k.addClass("red")}).trigger("progressbarchange");s.colorize&&s.color!="auto"&&k.addClass(s.color);s.animate&&k.addClass("animated");g.apply(this,arguments)}})(jQuery,this);
(function(c,g,m){var s=c.ui.progressbar.prototype._init;c.ui.progressbar.prototype.options.fx={animate:false,start:"now",duration:m,finish:m,refresh:16};c.ui.progressbar.prototype._init=function(){var k=this.options.fx;if(!k.animate)return s.apply(this,arguments);var h=function(b){c.error("Progressbar: "+b);return s.apply(this,arguments)};if(k.start=="now"||!(k.start instanceof Date))k.start=new Date;else if(k.start instanceof Date)if(k.start<new Date)return h("Cannot start in the past");if(isNaN(Number(k.duration))){if(!(k.finish instanceof
Date))return h("No valid duration or finish time given!")}else k.finish=new Date(k.start.getTime()+Number(k.duration)*1E3);if(k.finish<=k.start)return h("End time before start time? O.o");this.options.max=100;this.options.value=0;var o=k.finish-k.start;h=new Date;var t=this.element.find(".ui-progressbar-value"),q=false,j=0,a=0,p=-1,d=function(){if(!q&&a>0){q=true;t.show()}j=new Date-k.start;a=j/o*100;a=a>=0?a:0;t.css("width",a+"%");if(a>=100){clearInterval(p);this.value(100)}}.bind(this);if(h<k.start)setTimeout(function(){p=
setInterval(d.bind(this),k.refresh)},k.start-h-10);else p=setInterval(d.bind(this),k.refresh);s.apply(this,arguments)}})(jQuery,this);
(function(c){var g=c.ui.progressbar.prototype._init;c.ui.progressbar.prototype.options.showtitle="none";c.ui.progressbar.prototype.options.showvalue=false;c.ui.progressbar.prototype._init=function(){var m=this.options,s=this.element,k=c("<div>",{"class":"progress-title"});if(m.showtitle=="title")k.text(s.data("title")).insertBefore(s);else m.showtitle=="percentage"&&k.text(parseInt(this.options.value/this.options.max*100)+"%").insertBefore(s);if(m.showvalue){m.format=m.format||"";c("<div>",{"class":"progress-value",
text:(new Number(m.value)).numberFormat(m.format)+" / "+(new Number(m.max)).numberFormat(m.format)}).insertAfter(s)}g.apply(this,arguments)}})(jQuery,this);
(function(c,g,m,s,k){function h(){function j(){}var a={},p=["init","initialized","draw"];c.extend(a,{init:function(d){var b=a.$input=c(this);a.options=c.extend(true,{},a.defaults,d,b.data());if(!c.isArray(a.options.colors))a.options.colors=c.parseJSON(a.options.colors,true);d=c("<div>",{"class":"chart",height:a.options.height||b.parent().height()}).insertBefore(b);b.appendTo(d);if(b.is("table")){var f=b;d=a.parseTable(b);a.options.data=d.data;a.xlabels=d.xlabels;b=a.$input=c("<div>",{"class":"graph"});
b.insertAfter(f)}a.options.legend&&(a.$legend_box=c("<div>",{"class":"legend"}).insertBefore(b));d=parseInt(b.parent().css("margin-top"))+parseInt(b.parent().css("margin-bottom"));a.options.height?b.height(a.options.height):b.height(b.parent().height()-d-(a.options.legend?a.$legend_box.height():0)-(a.options.showTable?f.height():0));f&&!a.options.showTable&&f.remove();a.lastHoverItem=null;a.events={plotclick:function(l,n,i){if(i)switch(a.options.type){case "bars":a.options.events.click.call(b[0],
i.seriesIndex,i.datapoint[1],i);break;case "pie":a.options.events.click.call(b[0],i.seriesIndex,i.datapoint[1][0][1],i);break;default:a.options.events.click.call(b[0],i.seriesIndex,i.datapoint[1],i)}},plothover:function(l,n,i){if(i){switch(a.options.type){case "bars":a.options.events.hover.call(b[0],i.seriesIndex,i.datapoint[1],i);break;case "pie":a.options.events.hover.call(b[0],i.seriesIndex,i.datapoint[1][0][1],i);break;default:a.options.events.hover.call(b[0],i.seriesIndex,i.datapoint[1],i)}if(a.options.tooltip!==
false)if(a.lastHoverItem!=i.datapoint.toString()){a.lastHoverItem=i.datapoint.toString();c(".chart-tooltip").remove();l=i.datapoint[0];if(i.series.bars.order&&!a.options.horizontal)for(n=0;n<i.series.data.length;n++){if(i.series.data[n][3]==i.datapoint[0])l=i.series.data[n][0]}else if(a.options.horizontal)for(n=0;n<i.series.data.length;n++)if(i.series.data[n][3]==i.datapoint[1])l=i.series.data[n][1];n=parseInt(i.datapoint[1]);if(a.options.horizontal)n=parseInt(i.datapoint[0]);var r="";if(a.options.type==
"bars"){r=i.series.xaxis.ticks&&i.series.xaxis.ticks[i.dataIndex].label;if(a.options.horizontal)r=i.series.xaxis.ticks&&i.series.yaxis.ticks[i.dataIndex].label}else r=a.options.type=="pie"?i.series.xaxis.options.ticks&&i.series.xaxis.options.ticks[0][1]:i.series.xaxis.ticks&&i.series.xaxis.ticks[i.datapoint[0]].label;r||(r="");var w="";w=c.isFunction(a.options.tooltip)?a.options.tooltip.call(a,i.series.label,r,l,n):a.options.tooltip.replace("%label%",i.series.label).replace("%xlabel%",r).replace("%xval%",
l).replace("%yval%",n);var v=c("<div>",{"class":"chart-tooltip",text:w});l=i.pageX;i=i.pageY;if(a.options.type=="pie")c(s).mousemove(function(x){v.css({top:x.pageY+5,left:x.pageX+5})});else a.options.type=="bars"?v.css({top:i-23,left:l-10}):v.css({top:i+5,left:l+5});v.appendTo("body").fadeIn(100)}}else{c(".chart-tooltip").remove();a.lastHoverItem=null}}};for(var e in a.events)b.on(e+t,a.events[e]);a.setupChart();a.draw();a.initialized=true},parseTable:function(d){var b={data:[],xlabels:[]};if(a.options.series==
"columns"){var f=d.find("tbody th"),e=d.find("thead th");d=d.find("tbody tr");if(e.length)e=e.slice(1);var l=[];d.each(function(n,i){c(i).find("td").each(function(r,w){var v=w.innerHTML;l[r]=l[r]||[];isNaN(v)||l[r].push([n,parseInt(v)||0])})});d.eq(0).find("td").each(function(n){b.xlabels.push([n,f.eq(n).text()])});for(d=0;d<e.length;d++)b.data.push({label:e.eq(d).text(),data:l[d]})}else{f=d.find("thead th");e=d.find("tbody th");d=d.find("tbody tr");if(e.length)f=f.slice(1);d.each(function(n,i){var r=
[];c(i).find("td").each(function(w,v){var x=v.innerHTML;isNaN(x)||r.push([w,parseInt(x)||0])});b.data.push({label:e.eq(n).text(),data:a.options.type!="pie"?r:r[0][1]})});d.eq(0).find("td").each(function(n){b.xlabels.push([n,f.eq(n).text()])})}return b},setupChart:function(){if(a.options.type=="bars"){var d=a.options;if(!a.options.stacked){var b,f=1;for(b in d.data){var e=d.data[b];c.extend(true,e,{bars:{order:f++}})}}if(d.horizontal)for(b in d.data){e=d.data[b];if(e.data)for(f=0;f<e.data.length;f++){var l=
e.data[f][0];e.data[f][0]=e.data[f][1];e.data[f][1]=l}}c.extend(true,d.flot,{series:{points:{show:false},bars:{align:"center",order:d.stacked?null:true,show:true,border:false,fill:true,fillColor:null,horizontal:d.horizontal,barWidth:d.stacked?0.6:0.6/d.data.length,lineWidth:0},lines:{show:false},pie:{show:false}}})}else if(a.options.type=="pie"){d=a.options;c.extend(true,d.flot,{series:{points:{show:true},bars:{show:false},lines:{show:false},pie:{show:true,label:true,tilt:1,innerRadius:d.donut?d.donut:
0,radius:1}}})}else{d=a.options;c.extend(true,d.flot,{series:{points:{show:d.points},bars:{show:false},lines:{show:true,lineWidth:2,fill:d.fill==false?false:true,fillColor:d.fill==false?null:{colors:[{opacity:0},{opacity:0.15}]}},pie:{show:false}}})}a.options.flot=c.extend(true,{},{series:{stack:a.options.stacked?true:null},shadowSize:0,grid:{hoverable:a.options.tooltip!==false,clickable:true,color:"#ededed",markingsColor:"#939393",borderWidth:0},legend:{show:d.legend,position:"ne",container:a.options.legend?
a.$legend_box:null},colors:a.options.colors,xaxis:{color:"#ededed",labelWidth:30,font:{color:"#939393"}},yaxis:{color:"#ededed",font:{color:"#939393"}}},a.options.flot);if(a.xlabels&&!a.options.horizontal)a.options.flot.xaxis.ticks=a.xlabels;else if(a.options.horizontal)a.options.flot.yaxis.ticks=a.xlabels},draw:function(){c.plot(a.$input,a.options.data,a.options.flot)},initialized:false},c.fn[o]);c.extend(j,{publics:g.chain(a).keys().filter(g.bind(g.contains,g,p)),get:function(d){if(g.contains(p,
d))return a[d]},set:function(d,b){if(g.contains(p,d))a[d]=b}});return j}var o="chart",t=".mango_"+o,q=[];c.fn[o]=c.extend(function(j,a){var p=this,d=arguments;c(this).each(function(b,f){var e,l=c(this);if(e=q.filter(function(i){return i.el[0]==l[0]})[0])e=e.inst;else q.push({el:l,inst:e=h()});if(typeof j==="object"){a=j;j=k}j=j||"init";j!="init"&&!e.get("initialized")&&c.error("$.fn."+o+" was not initialzed. Please call $.fn."+o+"(options) first.");if(!(j=="init"&&e.get("initialized")))if(c.isFunction(e.get(j))){var n;
n=d[0]==a?c.makeArray(d):d.length>1?Array.prototype.slice.call(d,1):[a];e=e.get(j).apply(l,n);g.isUndefined(e)||(p=e)}else if(e.get(j))if(f)e.set(b,f);else p=e.get(b);else c.error("Method or property "+j+" does not exist on jQuery.fn."+o)});return p},{defaults:{data:[],height:null,type:"lines",points:true,stacked:false,legend:true,fill:null,donut:false,horizontal:false,colors:["#88bbc8","#ee7951","#bc71f","#e5c700"],tooltip:function(j,a,p,d){return(j?d+" "+j+" at ":"")+(this.options.flot.xaxis.ticks||
this.options.horizontal&&this.options.flot.yaxis.ticks?a!=""?a:p:"")},events:{click:function(){},hover:function(){}},series:"rows",showTable:false,flot:{}}})})(jQuery,_,this,document);
(function(c,g,m,s,k){function h(){function j(){}var a={},p=["format","formatPosNeg"];c.extend(a,{format:function(d,b){if(b=="%")return d+"%";else if(b=="+-"||b=="-+")return a.formatPosNeg(d);else if(b=="+-%"||b=="-+%")return a.formatPosNeg(d)+"%";return(new Number(d)).numberFormat(b)},formatPosNeg:function(d){return d!=0?a.format(d,"+0;-0"):d},init:function(d){var b=a.$element=c(this);a.options=c.extend(true,{},a.defaults,d,b.data());b=g.map(b,function(f){f=c(f);return f.is(a.options.selector)?f:
f.find(a.options.selector)});g.each(b,function(f){g.each(f[0].classList,function(e){if(g.isFunction(a[e])&&!f.data("initialized"))a[e](c(f))})});a.initialized=true},destroy:function(){a.$element.off(t);a.$element.find(a.options.selector).children().remove()},update:function(){a.destroy();a.init.apply(a.$element,a.options)},simple:function(d){var b=c.extend({},a.options.simple,d.data());if(b.format===0)b.format=d.attr("data-format");var f=a.format(b.value,b.format);b=b.title;if(/^\+/.test(f))d.addClass("positive");
else/^\-/.test(f)&&d.addClass("negative");b="<div class=title>"+b+"</div>";b+="<div class=value>"+f+"</div>";d.insert(b);d.is("a")&&d.addClass("link")},minichart:function(d){var b=c.extend({},a.options.minichart,d.data());if(b.format===0)b.format=d.attr("data-format");if(!c.isArray(b.values))b.data=c.parseJSON(b.values);if(/^\+/.test(b.total))d.addClass("positive");else/^\-/.test(b.total)&&d.addClass("negative");var f="<div class=left><div class=title>"+b.title+"</div>";f+="<div class=total>"+a.format(b.total,
b.format)+"</div></div>";f+="<div class=right><div class=minichart></div>";f+=g.isNumber(b.change)?"<div class=change>"+a.format(b.change,"+-%")+"</div>":"";d.insert(f);if(b.change==0&&!b.color)b.color="grey";else if(b.change>0&&!b.color)b.color="green";else if(b.change<0&&!b.color)b.color="red";var e="";(function(){var l=c('<div class="circular-fg '+(b.color||"")+'">').appendTo("body");e=l.css("color");l.remove()})();d.find(".minichart").sparkline(b.values,{type:"bar",barColor:e,negBarColor:e,disableTooltips:true});
d.find(".change").addClass(b.color);d.find(".total").addClass(b.color);d.children().equalHeight()},load:function(d){var b=c.extend({},a.options.load,d.data());if(b.format===0)b.format=d.attr("data-format");if(b.value>b.max)b.value=b.max;var f=a.format(b.value,b.format),e=a.format(b.max,b.format),l=a.format(b.min,b.format);f="<div class=value>"+f+"</div>";f+="<div class=bg></div>";f+="<div class=gauge></div>";f+="<div class=min>"+l+"</div>";f+="<div class=max>"+e+"</div>";d.insert(f);d.find(".gauge").rotate(180*
(b.value/b.max))},level:function(d){var b=c.extend({},a.options.level,d.data());d.insert('<div class="gauge-container"><div class="gauge'+(b.value==b.max?" full":"")+'" style="height:'+b.value/b.max*100+'%"></div></div>');var f="<div class=max>"+a.format(b.max,b.format.toString())+"</div>";f+="<div class=info><div class=value>"+a.format(b.value,b.format.toString())+"</div><div class=description>"+b.description+"</div></div>";d.insert(f);b=d.find(".gauge-container").height();d.find(".info").css("top",
Math.min(b+10,35+b-d.find(".gauge").height()))},pillar:function(d){var b=c.extend({},a.options.pillar,d.data());if(!c.isArray(b.data))b.data=c.parseJSON(b.data);var f=b.data.map(function(r){return r.val}).reduce(function(r,w){return r+w});d=d.insert('<div class="pillar-container"></div>');var e=d.height(),l="";c.each(b.data,function(){if(!(this.val<=0)){var r=e*(this.val/f);if(c.browser.webkit)r=Math.round(r);l+='<div class="inner '+(this.color||"green")+'" style="height:'+r+'px"><div class=level></div><div class=value>'+
a.format(this.val,b.format.toString())+"</div><div class=title>"+this.title+"</div></div>"}});d.insert(l);var n=d.find(".value");n=Math.max.apply(Math,n.map(function(){var r=c(this);return r.position().left+r.width()}).get())+parseInt(n.css("padding-right"));var i=d.find(".title").css("left",n+"px");i=Math.max.apply(Math,i.map(function(){return c(this).width()}).get());d.css("margin-right",n+i-d.find(".inner").width()+"px")},circular:function(d){var b=c.extend({},a.options.circular,d.data());if(b.format===
0)b.format=d.attr("data-format");if(b.valueformat===0)b.valueformat=d.attr("data-valueformat");if(b.list){if(!c.isArray(b.list))b.list=c.parseJSON(b.list);b.value=b.list.map(function(u){return g.isNumber(u.percent)?u.percent:u.val}).reduce(function(u,y){return u+y})}var f="<div class=value>";if(b.list&&b.format=="%"&&b.value>0)f+="+";f+=a.format(b.value,b.format);if(b.format!="%"&&b.displaymax)f+="<small>/"+a.format(b.max,b.format)+"</small>";f+="</div>";if(b.value==0&&!b.color)b.color="grey";else if(b.list&&
b.value>0&&!b.color)b.color="green";else if(b.list&&b.value<0&&!b.color)b.color="red";b.color&&d.addClass(b.color);var e="",l="";(function(){var u=c('<div class="circular-fg '+(b.color||"")+'">').appendTo("body"),y=c('<div class="circular-bg '+(b.color||"")+'">').appendTo("body");e=u.css("color");l=y.css("color");u.remove();y.remove()})();var n=d.insert("<canvas></canvas>"),i=n[0];i.getContext||(i=m.G_vmlCanvasManager.initElement(i));var r=n[0].getContext("2d"),w=n.width();n=n.height();var v=n/2;
i.height=n;i.width=w;var x=w/2,A=n/2;i=function(u,y){r.beginPath();r.moveTo(x,A);r.lineTo(x,0);m.G_vmlCanvasManager&&u==360?r.arc(x,A,y,-90*(Math.PI/180),-90*(Math.PI/180),false):r.arc(x,A,y,-90*(Math.PI/180),(-90+u)*(Math.PI/180),false);r.closePath();r.fill()};r.clearRect(0,0,w,n);r.fillStyle=l;i(360,v);if(b.value!=0){r.fillStyle=e;i(360*(Math.abs(b.value)/b.max),v)}r.fillStyle="#fff";i(360,v-b.width);d.append(f);if(b.list){var z="<ul>";c.each(b.list,function(){var u="";if(!g.isNumber(this.val)&&
g.isNumber(this.percent)){this.val=this.percent;this.percent=k;b.valueformat="%"}u=this.val>0?"pos":this.val<0?"neg":"neutr";z+="<li"+(u?" class="+u:"")+">";z+="<span class=title>"+this.title+"</span>";z+="<span class=value>"+(this.val>0?"+":"")+a.format(this.val,this.format||b.valueformat)+"</span>";if(this.percent)z+="<span class=percent>"+a.formatPosNeg(this.percent)+"%</span>";z+="</li>"});z+="</ul>";d.append(z)}},uptime:function(d){var b=c.extend({},a.options.uptime,d.data());if(b.servers&&!c.isArray(b.servers))b.servers=
c.parseJSON(b.servers);var f="<div class=overview>";c.each(b.servers,function(){f+="<div class=server>";f+='<div class="status '+(this.online?"online":"offline")+'">'+(this.online?b.lang.online:b.lang.offline)+"</div>";f+="<div class=name>"+this.name+"</div>";f+="</div>"});f+="</div>";d.insert(f);var e="<div class=left>";e+="<div class=title>"+b.lang[b.left]+"</div>";c.each(b.servers,function(){e+="<div class=entry>"+(this[b.left]||" ")+"</div>"});e+="</div>";var l="<div class=right>";l+="<div class=title>"+
b.lang[b.right]+"</div>";c.each(b.servers,function(){l+="<div class=entry>"+(this[b.right]||" ")+"</div>"});l+="</div>";d.insert("<div class=info>"+e+l+"</div>")},list:function(d){var b=c.extend({},a.options.list,d.data());if(!c.isArray(b.list))b.list=c.parseJSON(b.list);var f={up:"green",down:"red"},e="<ul>";c.each(b.list,function(){var l="";if(this.type){l+=this.type;l+=" "+(this.color||f[this.type])}if(this.link)l+=" link";l='<li class="'+l+'">';this.link&&(l+='<a href="'+this.link+'">');
l+="<div class=value>"+a.format(this.val,this.format||"")+"</div>";l+="<div class=title>"+this.title+"</div>";this.link&&(l+="</a>");l+="</li>";e+=l});e+="</ul>";d.insert(e);d.find(".value").equalWidth()},hlist:function(d){var b=c.extend({},a.options.hlist,d.data());if(!c.isArray(b.list))b.list=c.parseJSON(b.list);var f="<ul>";c.each(b.list,function(){var e="";if(this.color)e+=' class="'+this.color+'"';e="<li"+(e||"")+">";e+="<div class=value>"+a.format(this.val,this.format||"")+"</div>";e+="<div class=title>"+
this.title+"</div>";e+="</li>";f+=e});f+="</ul>";d.insert(f);d.on("show",function(){var e=d.find("li");e.css("width","");if(b.flexiwidth){d.parent().addClass("flexiwidth");e.css("width",1/e.length*100+"%")}else e.equalWidth()}).trigger("show")},initialized:false},c.fn[o]);c.extend(j,{privates:g.chain(a).keys().reject(g.bind(g.contains,g,p)),get:function(d){if(!g.contains(p,d))return a[d]},set:function(d,b){g.contains(p,d)||(a[d]=b)}});return j}var o="fullstats",t=".mango_"+o,q=[];c.fn[o]=c.extend(function(j,
a){var p=this,d=arguments;c(this).each(function(b,f){var e,l=c(this);if(e=g.filter(q,function(i){return i.el[0]==l[0]})[0])e=e.inst;else q.push({el:l,inst:e=h()});if(typeof j==="object"){a=j;j=k}j=j||"init";j!="init"&&!e.get("initialized")&&c.error("$.fn."+o+" was not initialzed. Please call $.fn."+o+"(options) first.");if(!(j=="init"&&e.get("initialized")))if(c.isFunction(e.get(j))){var n;n=d[0]==a?c.makeArray(d):d.length>1?Array.prototype.slice.call(d,1):[a];e=e.get(j).apply(l,n);g.isUndefined(e)||
(p=e)}else if(e.get(j))if(f)e.set(b,f);else p=e.get(b);else c.error("Method or property "+j+" does not exist on jQuery.fn."+o)});return p},{defaults:{selector:".stat",simple:{value:0,format:"0",title:""},minichart:{values:[],total:0,format:"0",title:"",change:null,color:""},load:{value:0,min:0,max:100,format:"%"},level:{value:50,max:100,format:"",description:""},pillar:{data:[],format:""},circular:{value:0,max:100,format:"%",valueformat:"",width:5,color:"",list:null,displaymax:true},uptime:{servers:[],
left:"lastDowntime",right:"response",lang:{online:"Online",offline:"Offline",lastDowntime:"Last downtime",response:"Response time"}},list:{list:[],color:""},hlist:{list:[],flexiwidth:false}}})})(jQuery,_,this,document);
(function(c,g,m,s,k){function h(){function j(){}var a={},p=["init","initialized","destroy"];c.extend(a,{init:function(d){var b=a.$element=c(this);a.options=c.extend(true,{},a.defaults,d,b.data());a.events={change:a.reflect};for(var f in a.events)b.on(f+t,a.events[f]);a.buildHtml();a.prepareHtml();a.initialized=true},buildHtml:function(){a.$element.attr("multiple",true);var d=c("<div class=dualselect>").insertAfter(a.$element);d.addClass(a.options.size);var b='<div class="left"><input type="text" class="ignore" placeholder="'+
a.options.lang.filterPlaceholder+'" /><select multiple class="ignore"></select><div class="counter"></div></div>';b+='<div class="buttons"><a class="button add"> > </a><a class="button addall"> >> </a><a class="button delall"> << </a><a class="button del"> < </a></div>';b+='<div class="right"><input type="text" class="ignore" placeholder="'+a.options.lang.filterPlaceholder+'" /><select multiple class="ignore"></select><div class="counter"></div></div>';
d.insert(b);a.$wrapper=d;b=d.find(".left");a.$leftFilter=b.find("input");a.$left=b.find("select");b=d.find(".right");a.$rightFilter=b.find("input");a.$right=b.find("select");d=d.find(".buttons");a.buttons={$add:d.find(".add"),$addall:d.find(".addall"),$del:d.find(".del"),$delall:d.find(".delall")};g.each(a.buttons,function(f){f.addClass(a.options.buttonClass)})},prepareHtml:function(){a.$originalState=a.$element.hide().clone();a.reflect();a.$element.parents("form").on("reset",function(){a.reset()});
var d=function(b){return function(){b.call(this);a.sort();a.reflectBack()}};g.each(a.buttons,function(b,f){b.click(d(a[f.replace("$","")]))});a.$left.dblclick(d(a.add));a.$right.dblclick(d(a.del));g.each({$left:a.$leftFilter,$right:a.$rightFilter},function(b,f){b.on("keyup"+t,function(e){if(e.keyCode==c.ui.keyCode.ESCAPE)this.value="";a.filter(this.value.toLowerCase(),a[f])})});a.sort()},reflect:function(){var d=a.$element.children(":selected").clone().map(function(){this.selected=false;return this}),
b=a.$element.children(":not(:selected)").clone().map(function(){this.selected=false;return this});a.$left.empty().append(b);a.$right.empty().append(d)},reflectBack:function(){var d=g.map(a.$right.children(),function(b){return b.value});a.$element.children().each(function(){this.selected=g.contains(d,this.value)});a.$element.change()},filter:function(d,b){a.reflect();b.children().filter(function(){return!(c(this).text().toLowerCase().indexOf(d)>=0)}).remove()},add:function(){a.$left.children(":selected").appendTo(a.$right)},
addall:function(){a.$left.children().appendTo(a.$right);a.sort()},del:function(){a.$right.children(":selected").appendTo(a.$left);a.sort()},delall:function(){a.$right.children().appendTo(a.$left);a.sort()},sort:function(){[a.$left,a.$right].forEach(function(d){var b=d.children().sort(function(f,e){var l=a.options.sortBy=="text"?f.text:c(f).attr("name"),n=a.options.sortBy=="text"?e.text:c(e).attr("name");return l>n?1:l<n?-1:0});d.empty().append(b)})},reset:function(){a.$element.children().replaceWith(a.$originalState.children());
a.reflect();a.$right.children().map(function(){this.selected=false;return this})},destroy:function(){a.$wrapper.remove();a.$element.off(t).show();q=g.filter(q,function(d){return d.el[0]!=a.$element[0]})},initialized:false},c.fn[o]);c.extend(j,{publics:g.chain(a).keys().filter(g.bind(g.contains,g,p)),get:function(d){if(g.contains(p,d))return a[d]},set:function(d,b){if(g.contains(p,d))a[d]=b}});return j}var o="dualselect",t=".mango_"+o,q=[];c.fn[o]=c.extend(function(j,a){var p=this,d=arguments;c(this).each(function(b,
f){var e,l=c(this);if(e=q.filter(function(i){return i.el[0]==l[0]})[0])e=e.inst;else q.push({el:l,inst:e=h()});if(typeof j==="object"){a=j;j=k}j=j||"init";j!="init"&&!e.get("initialized")&&c.error("$.fn."+o+" was not initialzed. Please call $.fn."+o+"(options) first.");if(!(j=="init"&&e.get("initialized")))if(c.isFunction(e.get(j))){var n;n=d[0]==a?c.makeArray(d):d.length>1?Array.prototype.slice.call(d,1):[a];e=e.get(j).apply(l,n);g.isUndefined(e)||(p=e)}else if(e.get(j))if(f)e.set(b,f);else p=e.get(b);
else c.error("Method or property "+j+" does not exist on jQuery.fn."+o)});return p},{defaults:{buttonClass:"flat",size:"medium",sortBy:"name",lang:{filterPlaceholder:"Filter entries..."}}})})(jQuery,_,this,document);