(function(a){a.idleTimer=function(f,c,d){d=a.extend({startImmediately:true,idle:false,enabled:true,timeout:3E4,events:"mousemove keydown DOMMouseScroll mousewheel mousedown touchstart touchmove"},d);c=c||document;var e=a(c),b=e.data("idleTimerObj")||{},g=function(h){if(typeof h==="number")h=undefined;h=a.data(h||c,"idleTimerObj");h.idle=!h.idle;var k=+new Date-h.olddate;h.olddate=+new Date;if(h.idle&&k<d.timeout){h.idle=false;clearTimeout(a.idleTimer.tId);if(d.enabled)a.idleTimer.tId=setTimeout(g,
d.timeout)}else{h=a.Event(a.data(c,"idleTimer",h.idle?"idle":"active")+".idleTimer");a(c).trigger(h)}},i=function(h){var k=h.data("idleTimerObj")||{};k.enabled=false;clearTimeout(k.tId);h.off(".idleTimer")};b.olddate=b.olddate||+new Date;if(typeof f==="number")d.timeout=f;else if(f==="destroy"){i(e);return this}else if(f==="getElapsedTime")return+new Date-b.olddate;e.on(a.trim((d.events+" ").split(" ").join(".idleTimer ")),function(){var h=a.data(this,"idleTimerObj");clearTimeout(h.tId);if(h.enabled){h.idle&&
g(this);h.tId=setTimeout(g,h.timeout)}});b.idle=d.idle;b.enabled=d.enabled;b.timeout=d.timeout;if(d.startImmediately)b.tId=setTimeout(g,b.timeout);e.data("idleTimer","active");e.data("idleTimerObj",b)};a.fn.idleTimer=function(f,c){c||(c={});if(this[0])return a.idleTimer(f,this[0],c);return this}})(jQuery);
(function(a){function f(d){return typeof d=="object"?d:{top:d,left:d}}var c=a.scrollTo=function(d,e,b){a(window).scrollTo(d,e,b)};c.defaults={axis:"xy",duration:parseFloat(a.fn.jquery)>=1.3?0:1,limit:true};c.window=function(){return a(window)._scrollable()};a.fn._scrollable=function(){return this.map(function(){if(!(!this.nodeName||a.inArray(this.nodeName.toLowerCase(),["iframe","#document","html","body"])!=-1))return this;var d=(this.contentWindow||this).document||this.ownerDocument||this;return/webkit/i.test(navigator.userAgent)||
d.compatMode=="BackCompat"?d.body:d.documentElement})};a.fn.scrollTo=function(d,e,b){if(typeof e=="object"){b=e;e=0}if(typeof b=="function")b={onAfter:b};if(d=="max")d=9E9;b=a.extend({},c.defaults,b);e=e||b.duration;b.queue=b.queue&&b.axis.length>1;if(b.queue)e/=2;b.offset=f(b.offset);b.over=f(b.over);return this._scrollable().each(function(){function g(p){h.animate(m,e,b.easing,p&&function(){p.call(this,k,b)})}if(d!=null){var i=this,h=a(i),k=d,j,m={},r=h.is("html,body");switch(typeof k){case "number":case "string":if(/^([+-]=?)?\d+(\.\d+)?(px|%)?$/.test(k)){k=
f(k);break}k=a(k,this);if(!k.length)return;case "object":if(k.is||k.style)j=(k=a(k)).offset()}a.each(b.axis.split(""),function(p,s){var n=s=="x"?"Left":"Top",q=n.toLowerCase(),l="scroll"+n,o=i[l],t=c.max(i,s);if(j){m[l]=j[q]+(r?0:o-h.offset()[q]);if(b.margin){m[l]-=parseInt(k.css("margin"+n))||0;m[l]-=parseInt(k.css("border"+n+"Width"))||0}m[l]+=b.offset[q]||0;if(b.over[q])m[l]+=k[s=="x"?"width":"height"]()*b.over[q]}else{n=k[q];m[l]=n.slice&&n.slice(-1)=="%"?parseFloat(n)/100*t:n}if(b.limit&&/^\d+$/.test(m[l]))m[l]=
m[l]<=0?0:Math.min(m[l],t);if(!p&&b.queue){o!=m[l]&&g(b.onAfterFirst);delete m[l]}});g(b.onAfter)}}).end()};c.max=function(d,e){var b=e=="x"?"Width":"Height",g="scroll"+b;if(!a(d).is("html,body"))return d[g]-a(d)[b.toLowerCase()]();b="client"+b;var i=d.ownerDocument.documentElement,h=d.ownerDocument.body;return Math.max(i[g],h[g])-Math.min(i[b],h[b])}})(jQuery);
(function(a){a.widget("ui.multiAccordion",{options:{active:0,showAll:null,hideAll:null,_classes:{accordion:"ui-accordion ui-widget ui-helper-reset ui-accordion-icons",h3:"ui-accordion-header ui-helper-reset ui-state-default ui-corner-all ui-accordion-icons",div:"ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom",divActive:"ui-accordion-content-active",span:"ui-accordion-header-icon ui-icon ui-icon-triangle-1-e",stateDefault:"ui-state-default",stateHover:"ui-state-hover"}},_create:function(){var c=
this,d=c.options,e=c.element,b=e.children("h3");e.children("div");e.addClass(d._classes.accordion);b.each(function(g){var i=a(this);i.addClass(d._classes.h3).prepend('<span class="{class}"></span>'.replace(/{class}/,d._classes.span));c._isActive(g)?c._showTab(i):c._hideTab(i)});e.children("div").each(function(){a(this).addClass(d._classes.div)});b.bind("click",function(g){g.preventDefault();g=a(this);var i={tab:g,content:g.next("div")};c._trigger("click",null,i);g.hasClass(d._classes.stateDefault)?
c._showTab(g):c._hideTab(g)});b.bind("mouseover",function(){a(this).addClass(d._classes.stateHover)});b.bind("mouseout",function(){a(this).removeClass(d._classes.stateHover)});c._trigger("init",null,e)},destroy:function(){var c=this.element,d=c.children("h3"),e=c.children("div"),b=this.options;c.children("h3").unbind("click mouseover mouseout");c.removeClass(b._classes.accordion);d.removeClass(b._classes.h3).removeClass("ui-state-default ui-corner-all ui-state-active ui-corner-top").children("span").remove();
e.removeClass(b._classes.div+" "+b._classes.divActive).show()},_showTab:function(c){var d=c.children("span.ui-icon"),e=c.next(),b=this.options;c.removeClass("ui-state-default ui-corner-all").addClass("ui-state-active ui-corner-top");d.removeClass("ui-icon-triangle-1-e").addClass("ui-icon-triangle-1-s");e.slideDown("fast",function(){e.addClass(b._classes.divActive)});this._trigger("tabShown",null,{tab:c,content:c.next("div")})},_hideTab:function(c){var d=c.children("span.ui-icon"),e=c.next(),b=this.options;
c.removeClass("ui-state-active ui-corner-top").addClass("ui-state-default ui-corner-all");d.removeClass("ui-icon-triangle-1-s").addClass("ui-icon-triangle-1-e");e.slideUp("fast",function(){e.removeClass(b._classes.divActive)});this._trigger("tabHidden",null,{tab:c,content:c.next("div")})},_isActive:function(c){var d=this.options;if(!(typeof d.active=="boolean"&&!d.active))if(d.active.length!=undefined)for(var e=0;e<d.active.length;e++){if(d.active[e]==c)return true}else return d.active==c;return false},
_getActiveTabs:function(){var c=[];this.element.children("div").each(function(d){var e=a(this);e.is(":visible")&&c.push({index:d,tab:e.prev("h3"),content:e})});return c.length==0?undefined:c},getActiveTabs:function(){var c=[];this.element.children("div").each(function(d){a(this).is(":visible")&&c.push(d)});return c.length==0?[-1]:c},_setActiveTabs:function(c){var d=this,e=this.element;typeof c!="undefined"&&e.children("div").each(function(b){var g=a(this).prev("h3");f(c,b)?d._showTab(g):d._hideTab(g)})},
_generateTabsArrayFromOptions:function(c){var d=[],e=this.element,b=e.children("h3").size();if(a.type(c)==="array")return c;else if(a.type(c)==="number")return[c];else if(a.type(c)==="string")switch(c.toLowerCase()){case "all":b=e.children("h3").size();for(c=0;c<b;c++)d.push(c);return d;case "none":return[-1]}},_setOption:function(c,d){a.Widget.prototype._setOption.apply(this,arguments);var e=this.element;switch(c){case "active":this._setActiveTabs(this._generateTabsArrayFromOptions(d));break;case "getActiveTabs":e=
this.element;var b;e.children("div").each(function(g){if(a(this).is(":visible")){b=b?b:[];b.push(g)}});return b.length==0?[-1]:b}}});var f=!Array.indexOf?function(c,d){for(var e=c.length+1;e-=1;)if(c[e-1]===d)return true;return false}:function(c,d){return c.indexOf(d)!==-1}})(jQuery);
(function(a){function f(b,g){if(!(b.originalEvent.touches.length>1)){b.preventDefault();var i=b.originalEvent.changedTouches[0],h=document.createEvent("MouseEvents");h.initMouseEvent(g,true,true,window,1,i.screenX,i.screenY,i.clientX,i.clientY,false,false,false,false,0,null);b.target.dispatchEvent(h)}}a.support.touch="ontouchend"in document;if(a.support.touch){var c=a.ui.mouse.prototype,d=c._mouseInit,e;c._touchStart=function(b){if(!(e||!this._mouseCapture(b.originalEvent.changedTouches[0]))){e=true;
this._touchMoved=false;f(b,"mouseover");f(b,"mousemove");f(b,"mousedown")}};c._touchMove=function(b){if(e){this._touchMoved=true;f(b,"mousemove")}};c._touchEnd=function(b){if(e){f(b,"mouseup");f(b,"mouseout");this._touchMoved||f(b,"click");e=false}};c._mouseInit=function(){this.element.bind("touchstart",a.proxy(this,"_touchStart")).bind("touchmove",a.proxy(this,"_touchMove")).bind("touchend",a.proxy(this,"_touchEnd"));d.call(this)}}})(jQuery);
(function(a,f,c){function d(j){j=j||location.href;return"#"+j.replace(/^[^#]*#?(.*)$/,"$1")}var e="hashchange",b=document,g,i=a.event.special,h=b.documentMode,k="on"+e in f&&(h===c||h>7);a.fn[e]=function(j){return j?this.bind(e,j):this.trigger(e)};a.fn[e].delay=50;i[e]=a.extend(i[e],{setup:function(){if(k)return false;a(g.start)},teardown:function(){if(k)return false;a(g.stop)}});g=function(){function j(){var l=d(),o=q(p);if(l!==p){n(p=l,o);a(f).trigger(e)}else if(o!==p)location.href=location.href.replace(/#.*/,
"")+o;r=setTimeout(j,a.fn[e].delay)}var m={},r,p=d(),s=function(l){return l},n=s,q=s;m.start=function(){r||j()};m.stop=function(){r&&clearTimeout(r);r=c};a.browser.msie&&!k&&function(){var l,o;m.start=function(){if(!l){o=(o=a.fn[e].src)&&o+d();l=a('<iframe tabindex="-1" title="empty"></iframe>').hide().one("load",function(){o||n(d());j()}).attr("src",o||"javascript:0").insertAfter("body")[0].contentWindow;b.onpropertychange=function(){try{if(event.propertyName==="title")l.document.title=b.title}catch(t){}}}};
m.stop=s;q=function(){return d(l.location.href)};n=function(t,w){var u=l.document,v=a.fn[e].domain;if(t!==w){u.title=b.title;u.open();v&&u.write('<script>document.domain="'+v+'"<\/script>');u.close();l.location.hash=t}}}();return m}()})(jQuery,this);Number.formatFunctions={count:0};Number.prototype.NaNstring="NaN";Number.prototype.posInfinity="Infinity";Number.prototype.negInfinity="-Infinity";Number.prototype.conditionRE=/\[(>=|<=|=|>|<)([0-9\.]+)\]/;
Number.prototype.numberFormat=function(a,f){if(isNaN(this))return Number.prototype.NaNstring;else if(this==+Infinity)return Number.prototype.posInfinity;else if(this==-Infinity)return Number.prototype.negInfinity;else Number.formatFunctions[a]==null&&Number.createNewFormat(a);return this[Number.formatFunctions[a]](f)};
Number.createNewFormat=function(a){var f="format"+Number.formatFunctions.count++;Number.formatFunctions[a]=f;f="Number.prototype."+f+" = function(context){\n";var c=a.split(";"),d="",e="",b=0,g="###.##";if(c.length<2&&a.match(Number.prototype.conditionRE)==null)f+=Number.createTerminalFormat(a);else{for(var i=0;a=c[i];i++)if((result=a.match(Number.prototype.conditionRE))!==null){a=a.replace(result[0],"");if(result[1]=="=")d+=Number.createConditionCode(result[1],result[2],a);else e+=Number.createConditionCode(result[1],
result[2],a)}else{switch(b){case 0:g=a;e+=Number.createConditionCode(">=",0,a);break;case 1:e+=Number.createConditionCode("<",0,a);break;case 2:d+=Number.createConditionCode("=",0,a);break;default:d="throw 'Too many semicolons in format string';"+d}b++}if(b==1)e+=Number.createConditionCode("<",0,g);else if(b==0)e+=Number.createConditionCode("all",0,g);f+=d+e}f+="}";eval(f)};
Number.createConditionCode=function(a,f,c){var d="";if(a=="all")return"\nreturn this.numberFormat('"+String.escape(c)+"', 1);";else{switch(a){case "=":d="==";break;case ">":d="> ";break;case "<":d="< ";break;case ">=":d=">=";break;case "<=":d="<=";break;default:throw"Error! Unrecognized condition format!";}return"\nif (this "+d+" "+parseFloat(f,10)+") {return this.numberFormat('"+String.escape(c)+"', 1);}"}};
Number.createTerminalFormat=function(a){if(a.length>0&&a.search(/[0#?]/)==-1)return"return '"+String.escape(a)+"';\n";var f="var val = (context == null) ? new Number(this) : Math.abs(this);\n",c=false,d=a,e="",b=0,g=0,i=0,h=false,k="";if(j=a.match(/\..*(e)([+-]?)(0+)/i)){k=j[1];h=j[2]=="+";i=j[3].length;a=a.replace(/(e)([+-]?)(0+)/i,"")}var j=a.match(/^([^.]*)\.(.*)$/);if(j){d=j[1].replace(/\./g,"");e=j[2].replace(/\./g,"")}if(a.indexOf("%")>=0)f+="val *= 100;\n";if(j=d.match(/(,+)(?:$|[^0#?,])/))f+=
"val /= "+Math.pow(1E3,j[1].length)+"\n;";if(d.search(/[0#?],[0#?]/)>=0)c=true;if(j||c)d=d.replace(/,/g,"");if(j=d.match(/0[0#?]*/))b=j[0].length;if(j=e.match(/[0#?]*/))g=j[0].length;if(i>0)f+="var sci = Number.toScientific(val,"+b+", "+g+", "+i+", "+h+");\nvar arr = [sci.l, sci.r];\n";else{if(a.indexOf(".")<0){f+="var sign = (this < 0 && context == null) ? -1 : 1;\n";f+="val = Math.round(val*sign)*sign;\n"}f+="var arr = val.round("+g+").toFixed("+g+").split('.');\n";f+="arr[0] = (val < 0 ? '-' : '') + String.leftPad((val < 0 ? arr[0].substring(1) : arr[0]), "+
b+", '0');\n"}if(c)f+="arr[0] = Number.addSeparators(arr[0]);\n";f+="arr[0] = Number.injectIntoFormat(arr[0].reverse(), '"+String.escape(d.reverse())+"', true).reverse();\n";if(g>0)f+="arr[1] = Number.injectIntoFormat(arr[1], '"+String.escape(e)+"', false);\n";if(i>0)f+="arr[1] = arr[1].replace(/(\\d{"+g+"})/, '$1"+k+"' + sci.s);\n";return f+"return arr.join('.');\n"};
Number.toScientific=function(a,f,c,d,e){var b={l:"",r:"",s:""},g="",i=Math.abs(a).toFixed(f+c+1).trim("0");c=Math.round(new Number(i.replace(".","").replace(RegExp("(\\d{"+(f+c)+"})(.*)"),"$1.$2"))).toFixed(0);if(c.length>=f)c=c.substring(0,f)+"."+c.substring(f);else c+=".";b.s=i.indexOf(".")-i.search(/[1-9]/)-c.indexOf(".");b.s<0&&b.s++;b.l=(a<0?"-":"")+String.leftPad(c.substring(0,c.indexOf(".")),f,"0");b.r=c.substring(c.indexOf(".")+1);if(b.s<0)g="-";else if(e)g="+";b.s=g+String.leftPad(Math.abs(b.s).toFixed(0),
d,"0");return b};Number.prototype.round=function(a){if(a>0){var f=this.toFixed(Math.min(a+10,20)).match(RegExp("(-?\\d*).(\\d{"+a+"})(\\d)\\d*$"));if(f&&f.length){var c=f[1].charAt(0)=="-"?-1:1,d=String.leftPad(Math.round(f[2]+"."+f[3]),a,"0");return d.length>a?new Number(f[1])+c:new Number(f[1]+"."+d)}}return this};
Number.injectIntoFormat=function(a,f,c){var d=0,e=0,b="",g=a.charAt(a.length-1)=="-";if(g)a=a.substring(0,a.length-1);for(;d<f.length&&e<a.length&&f.substring(d).search(/[0#?]/)>=0;){if(f.charAt(d).match(/[0#?]/)){b+=a.charAt(e)!="-"?a.charAt(e):"0";e++}else b+=f.charAt(d);++d}if(g&&e==a.length)b+="-";if(e<a.length){if(c)b+=a.substring(e);if(g)b+="-"}if(d<f.length)b+=f.substring(d);return b.replace(/#/g,"").replace(/\?/g," ")};
Number.addSeparators=function(a){return a.reverse().replace(/(\d{3})/g,"$1,").reverse().replace(/^(-)?,/,"$1")};String.prototype.reverse=function(){for(var a="",f=this.length;f>0;--f)a+=this.charAt(f-1);return a};String.prototype.trim=function(a){a||(a=" ");return this.replace(RegExp("^"+a+"+|"+a+"+$","g"),"")};String.leftPad=function(a,f,c){a=new String(a);if(c==null)c=" ";for(;a.length<f;)a=c+a;return a};String.escape=function(a){return a.replace(/(')/g,"\\$1").replace(/[\r\n]/g,"")};